// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using libraryMVC_.Data;

namespace site.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("libraryMVC.Models.Emanet", b =>
                {
                    b.Property<int>("EmanetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmanetGeriAlmaTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetIslemTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetNot")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetTeslimEdildi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmanetVermeTarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UyeNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmanetNo");

                    b.ToTable("Emanetler");
                });

            modelBuilder.Entity("libraryMVC.Models.Kitap", b =>
                {
                    b.Property<int>("KitapNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAd")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapBaskiYil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapDil")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapSayfaSayi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapYayinEvi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapYazari")
                        .HasColumnType("TEXT");

                    b.HasKey("KitapNo");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("libraryMVC.Models.Uye", b =>
                {
                    b.Property<int>("UyeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UyeAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("UyeAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("UyeEposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("UyeSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("UyeTelefon")
                        .HasColumnType("TEXT");

                    b.HasKey("UyeNo");

                    b.ToTable("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
